root: true

env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-restricted-syntax: ['error', 'FunctionExpression', 'WithStatement']
  